services:
  - type: web
    name: gomoku-game
    env: node
    buildCommand: bash ./build.sh
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
