services:
  - type: web
    name: gomoku-game
    env: node
    plan: free
    buildCommand: npm run build:render
    startCommand: cd server && node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
