services:
  - type: web
    name: gomoku-game
    env: node
    plan: free
    buildCommand: |
      npm install
      node build-for-render.js
    startCommand: cd server && node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
