services:
  - type: web
    name: gomoku-game
    env: node
    buildCommand: |
      # TypeScriptエラーを無視してビルドを続行
      set +e
      bash ./build.sh
      set -e
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
